openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Picture of the day
  license:
    name: MIT
servers:
  - url: http://localhost:8080/
paths:
  /ping:
    get:
      responses:
        '200':
          description: OK
